package sync

type ApiGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	SyncApi
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
