version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    image: 244395036/qa-ui:v0.0.1
    container_name: gva-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    image: 244395036/qa-server:v2022.02.13.08.49.16
    container_name: gva-server
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - /root/.ssh:/root/.ssh
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:5.7
    container_name: gva-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    volumes:
      - ~/Documents/docker-mysql/data:/var/lib/mysql 
    environment:
      MYSQL_DATABASE: 'gva' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    container_name: gva-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    networks:
      network:
        ipv4_address: 177.7.0.14