package autocode

type ServiceGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	ProjectService
	ModuleService
	EnvConfigService
	ApiInfoService
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
