package autocode

type ServiceGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	//organization.ProjectService
	//api_test.ModuleService
	//organization.EnvConfigService
	//api_test.ApiInfoService
	//api_test.ApiTestcaseService
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
