package autocode

type ServiceGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	//organization.ProjectService
	//apitest.ModuleService
	//organization.EnvConfigService
	//apitest.ApiInfoService
	//apitest.ApiTestcaseService
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
