package api_test

type ServiceGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	ModuleService
	//ApiInfoService
	ApiTestcaseService
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
