package apiTest

type RouterGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	ApiTestcaseRouter
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
