package autocode

import (
	"github.com/jizi19911101/gin-vue-admin/server/router/api_test"
	"github.com/jizi19911101/gin-vue-admin/server/router/project"
)

type RouterGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	project.ProjectRouter
	api_test.ModuleRouter
	project.EnvConfigRouter
	api_test.ApiInfoRouter
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
