package autocode

type RouterGroup struct {
	// Code generated by github.com/jizi19911101/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	//organization.ProjectRouter
	//api_test.ModuleRouter
	//organization.EnvConfigRouter
	//api_test.ApiInfoRouter
	// Code generated by github.com/jizi19911101/gin-vue-admin/server End; DO NOT EDIT.
}
