name: gin-vue-admin docker build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"

jobs:
  server:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Build image
        id: vars 
        shell: bash
        run: |
          docker login -u 244395036 -p ${{ secrets.DOCKER_TOKEN }}
          cd server
          docker build -t 244395036/qa-server:v0.0.1 .
          docker push 244395036/qa-server:v0.0.1

  ui:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Build image
        id: vars 
        shell: bash
        run: |
          docker login -u 244395036 -p ${{ secrets.DOCKER_TOKEN }}
          cd web
          docker build -t 244395036/qa-ui:v0.0.1 .
          docker push 244395036/qa-ui:v0.0.1