name: gin-vue-admin docker build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "./db/**"
      - "**.md"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Get git revision
        id: vars
        shell: bash
        run: |
          docker login -u 244395036 -p ${{ secrets.DOCKER_TOKEN }}
          cd server
          docker build -t qa-server:v0.0.1 .
          docker push qa-server:v0.0.1

